services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001

  - type: static-site
    name: frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build